map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      '';
}

server {
    listen 80;
    listen [::]:80;
    server_name _;

    root __PROJECT_ROOT__/web/public;

    location /_next/static/ {
        alias __PROJECT_ROOT__/web/.next/static/;
        expires 365d;
        access_log off;
    }

    location / {
        try_files $uri @next;
    }

    location /download {
        alias __PROJECT_ROOT__/mobile/android/app/build/outputs/apk/release/;

        location = /download {
            return 302 /download/locarc.apk;
        }

        types { }
        default_type application/vnd.android.package-archive;

        add_header Content-Disposition 'attachment; filename="locarc.apk"' always;
        add_header X-Content-Type-Options nosniff always;
        add_header Cache-Control "no-cache" always;

        try_files /locarc.apk =404;
    }

    location @next {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 8000;
    listen [::]:8000;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 90;
    }
}