/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as userDetailsRouteImport } from './routes/(user)/details'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as adminSettingsRouteImport } from './routes/(admin)/settings'
import { Route as adminSdrRouteImport } from './routes/(admin)/sdr'
import { Route as adminReplayRouteImport } from './routes/(admin)/replay'
import { Route as adminMapRouteImport } from './routes/(admin)/map'
import { Route as adminControllersRouteImport } from './routes/(admin)/controllers'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const userDetailsRoute = userDetailsRouteImport.update({
  id: '/(user)/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const adminSettingsRoute = adminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminSdrRoute = adminSdrRouteImport.update({
  id: '/sdr',
  path: '/sdr',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminReplayRoute = adminReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminMapRoute = adminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminControllersRoute = adminControllersRouteImport.update({
  id: '/controllers',
  path: '/controllers',
  getParentRoute: () => adminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controllers': typeof adminControllersRoute
  '/map': typeof adminMapRoute
  '/replay': typeof adminReplayRoute
  '/sdr': typeof adminSdrRoute
  '/settings': typeof adminSettingsRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/details': typeof userDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/controllers': typeof adminControllersRoute
  '/map': typeof adminMapRoute
  '/replay': typeof adminReplayRoute
  '/sdr': typeof adminSdrRoute
  '/settings': typeof adminSettingsRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/details': typeof userDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(admin)/controllers': typeof adminControllersRoute
  '/(admin)/map': typeof adminMapRoute
  '/(admin)/replay': typeof adminReplayRoute
  '/(admin)/sdr': typeof adminSdrRoute
  '/(admin)/settings': typeof adminSettingsRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(user)/details': typeof userDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/controllers'
    | '/map'
    | '/replay'
    | '/sdr'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/controllers'
    | '/map'
    | '/replay'
    | '/sdr'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/details'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(auth)'
    | '/(admin)/controllers'
    | '/(admin)/map'
    | '/(admin)/replay'
    | '/(admin)/sdr'
    | '/(admin)/settings'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(user)/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminRouteRoute: typeof adminRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  userDetailsRoute: typeof userDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(user)/details': {
      id: '/(user)/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof userDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(admin)/settings': {
      id: '/(admin)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof adminSettingsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/sdr': {
      id: '/(admin)/sdr'
      path: '/sdr'
      fullPath: '/sdr'
      preLoaderRoute: typeof adminSdrRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/replay': {
      id: '/(admin)/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof adminReplayRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/map': {
      id: '/(admin)/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof adminMapRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/controllers': {
      id: '/(admin)/controllers'
      path: '/controllers'
      fullPath: '/controllers'
      preLoaderRoute: typeof adminControllersRouteImport
      parentRoute: typeof adminRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminControllersRoute: typeof adminControllersRoute
  adminMapRoute: typeof adminMapRoute
  adminReplayRoute: typeof adminReplayRoute
  adminSdrRoute: typeof adminSdrRoute
  adminSettingsRoute: typeof adminSettingsRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminControllersRoute: adminControllersRoute,
  adminMapRoute: adminMapRoute,
  adminReplayRoute: adminReplayRoute,
  adminSdrRoute: adminSdrRoute,
  adminSettingsRoute: adminSettingsRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminRouteRoute: adminRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  userDetailsRoute: userDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
