apply plugin: 'com.android.library'

group = 'com.locarc.mobile.hackrf'
version = '0.7.6'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

def useManagedAndroidSdkVersions = false
if (useManagedAndroidSdkVersions) {
  useDefaultAndroidSdkVersions()
} else {
  buildscript {
    ext.safeExtGet = { prop, fallback ->
      rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
    }
  }
  project.android {
    compileSdkVersion safeExtGet("compileSdkVersion", 36)
    defaultConfig {
      minSdkVersion safeExtGet("minSdkVersion", 24)
      targetSdkVersion safeExtGet("targetSdkVersion", 36)
    }
  }
}

android {
  namespace "com.locarc.mobile.hackrf"
  defaultConfig {
    versionCode 1
    versionName "0.7.6"
    ndk {
      abiFilters "arm64-v8a", "armeabi-v7a"
    }
    externalNativeBuild {
      cmake {
        cppFlags "-std=c++17"
        cFlags "-std=c11"
        arguments "-DANDROID_STL=c++_shared"
      }
    }
  }
  externalNativeBuild {
    cmake {
      path "CMakeLists.txt"
      version "3.22.1"
    }
  }
  lintOptions {
    abortOnError false
  }
}
